EP.Conference/Models/Conference/ConferenceFields.cs
using System;
using System.ComponentModel.DataAnnotations;

// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace EP.Conference.Models.Conference
{
    public class ConferenceFields
    {

        [Key] public string GGUID { get; set; }

        public bool DISABLEWAITLIST { get; set; }

        public bool EV_ALLOWADDRCHANGE { get; set; }

        public bool EV_ALLOWPUBLICREGISTRATION { get; set; }

        public bool EV_ALLOWREGTOAPP { get; set; }

        public bool EV_AUTOCONFIRMREG { get; set; }

        [Display(Name = "Kraj")]
        public DateTime EV_ENDDT { get; set; }

        public bool EV_FURTHERPARTICIPANTS { get; set; }

        [Display(Name = "Početak")]
        public DateTime EV_STARTDT { get; set; }

        [Display(Name = "Naziv konferencije")]
        public string EV_TITLE { get; set; }

        [Display(Name = "Lokacija")]
        public string EV_VENUE { get; set; }

        public int FOREIGNEDITPERMISSION { get; set; }

        public bool GWRTFINFOFLAG { get; set; }

        public DateTime INSERTTIMESTAMP { get; set; }

        public string INSERTUSER { get; set; }

        public string OWNERGUID { get; set; }

        public string OWNERNAME { get; set; }

        public bool RESOURCERESERVATION { get; set; }

        public DateTime UPDATETIMESTAMP { get; set; }

        public string UPDATEUSER { get; set; }
    }
}

EP.Conference/Models/Conference/ConferenceViewModel.cs
using EP.Conference.Models.Shared;

namespace EP.Conference.Models.Conference
{
    public class ConferenceViewModel
    {
        public string ObjectType { get; set; }

        public string Id { get; set; }

        public ConferenceFields Fields { get; set; }

        public Links Links { get; set; }
    }
}

EP.Conference/Models/Speakers/Details/SpeakerDetailsViewModel.cs
using EP.Conference.Models.Shared;

namespace EP.Conference.Models.Speakers.Details
{
    public class SpeakerDetailsViewModel
    {
        public string ObjectType { get; set; }

        public string Id { get; set; }

        public SpeakersDetailsFields Fields { get; set; }

        public Links Links { get; set; }
    }
}

EP.Conference/Models/Speakers/Details/SpeakersDetailsFields.cs
using System;

// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

namespace EP.Conference.Models.Speakers.Details
{
    public class SpeakersDetailsFields
    {
        public string GWBRANCH { get; set; }
        public bool BIRTHDAYGREETINGS { get; set; }
        public int BLOCKED_EMAILS { get; set; }
        public int CBADDRESS { get; set; }
        public int CBFAX1 { get; set; }
        public int CBFAX2 { get; set; }
        public int CBFAX3 { get; set; }
        public int CBIM { get; set; }
        public int CBMAIL { get; set; }
        public int CBPHONE1 { get; set; }
        public int CBPHONE2 { get; set; }
        public int CBPHONE3 { get; set; }
        public int CBWEB { get; set; }
        public string CHRISTIANNAME { get; set; }
        public bool CHRISTMASGREETINGS { get; set; }
        public string COMPNAME { get; set; }
        public int FOREIGNEDITPERMISSION { get; set; }
        public string GEOCODESTATUS { get; set; }
        public int GEOCODESTATUSNUMBER { get; set; }
        public string GGUID { get; set; }
        public string GWADDRESSFORMAT { get; set; }
        public bool GWDEACTIVATED { get; set; }
        public bool GWDUPLICATECHECK { get; set; }
        public bool GWIDENTITYEXIST { get; set; }
        public bool GWISCOMPANY { get; set; }
        public bool GWISCONTACT { get; set; }
        public bool GWISEMPLOYEE { get; set; }
        public bool GWISEXTERNALEMPLOYEE { get; set; }
        public bool GWKEEPCONTACTSYNCHRON { get; set; }
        public string GWPHONETIC_CHRISTIANNAME { get; set; }
        public string GWPHONETIC_COMPNAME { get; set; }
        public string GWPHONETIC_NAME { get; set; }
        public bool GWSSERVICEPASSWORDSET { get; set; }
        public bool HDBLOCKEDFORSUPPORT { get; set; }
        public DateTime INSERTTIMESTAMP { get; set; }
        public string INSERTUSER { get; set; }
        public int INXMAIL_BOUNCES { get; set; }
        public string NAME { get; set; }
        public string OWNERGUID { get; set; }
        public string OWNERNAME { get; set; }
        public DateTime UPDATETIMESTAMP { get; set; }
        public string UPDATEUSER { get; set; }
    }
}

EP.Conference/Controllers/ConferenceController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using EP.Conference.Contracts;
using EP.Conference.Models.Conference;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EP.Conference.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly IGenesisService _service;

        public ConferenceController(IGenesisService service)
        {
            _service = service;
        }

        // GET: ConferenceFields
        public async Task<IActionResult> Index()
        {
            var response = await _service.GetConferencesAsync();

            return View(response.Select(x => x.Fields));
        }

        // GET: ConferenceFields/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetConferenceAsync(id);

            if (response == null) return NotFound();

            return View(response.Fields);
        }

        // GET: ConferenceFields/Create
        public IActionResult Create()
        {
            var model = new ConferenceFields {EV_STARTDT = DateTime.Now, EV_ENDDT = DateTime.Now.AddDays(1)};

            return View(model);
        }

        // POST: ConferenceFields/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EV_TITLE,EV_STARTDT,EV_ENDDT,EV_VENUE")]ConferenceFields conferenceFields)
        {
            await _service.CreateConferenceAsync(conferenceFields);
            if (ModelState.IsValid) return RedirectToAction(nameof(Index));
            return View(conferenceFields);
        }

        // GET: ConferenceFields/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetConferenceAsync(id);

            if (response == null) return NotFound();

            TempData["Etag"] = response.Fields.INSERTUSER;

            return View(response.Fields);
        }

        // POST: ConferenceFields/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("GGUID,EV_TITLE,EV_STARTDT,EV_ENDDT,EV_VENUE,INSERTUSER")]
            ConferenceFields conferenceFields)
        {
            if (id != conferenceFields.GGUID) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    conferenceFields.INSERTUSER = TempData["Etag"].ToString();
                    await _service.UpdateConferenceAsync(conferenceFields);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConferenceFieldsExists(conferenceFields.GGUID))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(conferenceFields);
        }

        // GET: ConferenceFields/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetConferenceAsync(id);

            if (response == null) return NotFound();

            return View(response.Fields);
        }

        // POST: ConferenceFields/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _service.DeleteConferenceAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool ConferenceFieldsExists(string id)
        {
            //return _context.Conferences.Any(e => e.GGUID == id);
            return true;
        }
    }
}

EP.Conference/Controllers/RegistrationController.cs
using System.Linq;
using System.Threading.Tasks;
using EP.Conference.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace EP.Conference.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly IGenesisService _service;

        public RegistrationController(IGenesisService service)
        {
            _service = service;
        }

        // GET: Registration
        public async Task<IActionResult> Index(string id)
        {
            var response = await _service.GetRegistrationsAsync();
            var fields = response.Select(x => x.Fields);
            var filtered = fields.Where(x => x.REG_EVENTGUID.Contains(id)).ToList();

            return View(filtered);
        }

        // GET: Registration/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetRegistrationAsync(id);

            if (response == null) return NotFound();

            return View(response.Fields);
        }

        // GET: Registration/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null) return NotFound();

            var response = await _service.GetRegistrationAsync(id);

            if (response == null) return NotFound();

            return View(response.Fields);
        }

        // POST: Registration/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _service.DeleteRegistrationAsync(id);

            return RedirectToAction(nameof(Index), nameof(Conference));
        }
    }
}

EP.Conference/Views/Conference/Create.cshtml
@model EP.Conference.Models.Conference.ConferenceFields

<h4>ConferenceFields</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EV_TITLE" class="control-label"></label>
                <input asp-for="EV_TITLE" class="form-control" />
                <span asp-validation-for="EV_TITLE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EV_STARTDT" class="control-label"></label>
                <input asp-for="EV_STARTDT" class="form-control" />
                <span asp-validation-for="EV_STARTDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EV_ENDDT" class="control-label"></label>
                <input asp-for="EV_ENDDT" class="form-control" />
                <span asp-validation-for="EV_ENDDT" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="EV_VENUE" class="control-label"></label>
                <input asp-for="EV_VENUE" class="form-control" />
                <span asp-validation-for="EV_VENUE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EP.Conference/Views/Conference/Delete.cshtml
@model EP.Conference.Models.Conference.ConferenceFields

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ConferenceFields</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EV_TITLE)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EV_TITLE)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EV_STARTDT)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EV_STARTDT)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EV_ENDDT)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EV_ENDDT)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EV_VENUE)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EV_VENUE)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GGUID" />
        <input type="submit" value="Izbriši" class="btn btn-danger" /> |
        <a asp-action="Index">Nazad na listu</a>
    </form>
</div>

EP.Conference/Views/Conference/Details.cshtml
@model EP.Conference.Models.Conference.ConferenceFields

<div>
    <h4>ConferenceFields</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EV_TITLE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EV_TITLE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EV_STARTDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EV_STARTDT)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EV_ENDDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EV_ENDDT)
        </dd>
      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EV_VENUE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EV_VENUE)
        </dd>
    
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GGUID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EP.Conference/Views/Conference/Edit.cshtml
@model EP.Conference.Models.Conference.ConferenceFields

<h4>ConferenceFields</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GGUID" />
            <div class="form-group">
                <label asp-for="EV_TITLE" class="control-label"></label>
                <input asp-for="EV_TITLE" class="form-control" />
                <span asp-validation-for="EV_TITLE" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EV_STARTDT" class="control-label"></label>
                <input asp-for="EV_STARTDT" class="form-control" />
                <span asp-validation-for="EV_STARTDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EV_ENDDT" class="control-label"></label>
                <input asp-for="EV_ENDDT" class="form-control" />
                <span asp-validation-for="EV_ENDDT" class="text-danger"></span>
            </div>

         
            <div class="form-group">
                <label asp-for="EV_VENUE" class="control-label"></label>
                <input asp-for="EV_VENUE" class="form-control" />
                <span asp-validation-for="EV_VENUE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EP.Conference/Views/Conference/Index.cshtml
@model IEnumerable<EP.Conference.Models.Conference.ConferenceFields>

@{
    ViewData["Title"] = "View";
}

<h1>Lista konferencija</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EV_TITLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EV_STARTDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EV_ENDDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EV_VENUE)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EV_TITLE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EV_STARTDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EV_ENDDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EV_VENUE)
            </td>
            <td>
                <a asp-action="Index" asp-controller="Registration" asp-route-id="@item.GGUID">Predavači</a> |
                <a asp-action="Edit" asp-route-id="@item.GGUID">Uredi</a> |
                <a asp-action="Details" asp-route-id="@item.GGUID">Detalji</a> |
                <a asp-action="Delete" asp-route-id="@item.GGUID">Izbriši</a>
            </td>
        </tr>
}
    </tbody>
</table>